name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: macos-10.15
    steps:
    # This step checks out the code using github actions (prebuilt module)
    - uses: actions/checkout@v2
    # This step sets up the .NET environment required for application build
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    # Build and test phase of pipeline
    - name: Dotnet Restore
      run: dotnet restore
    - name: Dotnet Build
      run: dotnet build --no-restore -c Release
    - name: Dotnet Publish
      run: dotnet publish -c Release
    - name: Unit Tests - Business
      run: dotnet test tests/DevOpsChallenge.SalesApi.Business.UnitTests/bin/Release/net5.0/DevOpsChallenge.SalesApi.Business.UnitTests.dll --collect:"XPlat Code Coverage"
    - name: Echo Test Results
      run: cat $(find TestResults -name coverage.cobertura.xml) 
    - name: Echo Build Version
      run: git describe --all --long | cut -d "-" -f 3
