name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-image:

    runs-on: ubuntu-latest

    steps:
    # This step checks out the code using github actions (prebuilt module)
    - uses: actions/checkout@v2
    # This step sets up the .NET environment required for application build
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    # Build and test phase of pipeline
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build -c Release --no-restore
    - name: Test
      run: dotnet test --no-build /p:CollectCoverage=true 
